apiVersion: apps.isadba.com/v1
kind: Application
metadata:
  name: application-sample
spec:
  # TODO(user): Add fields here
  replicas: 2
  template:
    spec:
      containers:
      - image: nginx:1.8.1
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP